### ISSUE TITLE
FFT example doesn't compile.

### ISSUE THREAD

**Issue by goncasmage1** [micknoise/Maximilian#53]
Hi, i'm really interested in using Maximillian's FFT capabilities, but when i run the fft example from the examples folder in VS 2015, it doesn't compile? Does anyone have a solution? Thanks in advance!

**Comment by admin96** [comment]
What is the problem? What are the compiler errors?

**Comment by goncasmage1** [comment]
1>d:\downloads\maximilian-master\maximilian.h(304): warning C4244: '=': conversion from 'double' to 'short', possible loss of data
1>d:\downloads\maximilian-master\maximilian.h(374): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10150.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
1>d:\downloads\maximilian-master\maximilian.h(518): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
1>d:\downloads\maximilian-master\maximilian.h(543): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
1>d:\downloads\maximilian-master\maximilian.h(544): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
1>d:\downloads\maximilian-master\main.cpp(78): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>main.obj : error LNK2019: unresolved external symbol "public: __thiscall maxiFFT::~maxiFFT(void)" (??1maxiFFT@@QAE@XZ) referenced in function "void __cdecl `dynamic atexit destructor for 'myFFT''(void)" (??__FmyFFT@@YAXXZ)
1>main.obj : error LNK2019: unresolved external symbol "public: void __thiscall maxiFFT::setup(int,int,int)" (?setup@maxiFFT@@QAEXHHH@Z) referenced in function "void __cdecl setup(void)" (?setup@@YAXXZ)
1>main.obj : error LNK2019: unresolved external symbol "public: bool __thiscall maxiFFT::process(float)" (?process@maxiFFT@@QAE_NM@Z) referenced in function "void __cdecl play(double *)" (?play@@YAXPAN@Z)
1>D:\Downloads\Maximilian-master\maximilianTestWindowsVS2015\Debug\maximilianTestWindowsVS2015.exe : fatal error LNK1120: 3 unresolved externals

**Comment by admin96** [comment]
So, most of what is printed in the output just consists of warnings. These can be ignored. However, you're also getting linker errors which cannot be ignored as your executable will not work if your compilation has linker errors. This problem is not occurring because of the library's code. _**The linker errors are caused by improperly linking the Maximillian library**_. You need to *compile and link* the library code!

**Comment by goncasmage1** [comment]
Ok thanks :) i'll look into that! it's basically going to the dependencies options and linking them to the libs folder right?

**Comment by admin96** [comment]
Yeah. Its a little tricky to figure out how to link/compile libraries using VS but once you do it correctly, it is difficult to forget. If you add the following two lines at the start of your code, it will remove the warnings from the compiler output:

#pragma warning(disable 4996)
#pragma warning(disable 4244)

Now, all you will have left is the warnings. If you look at those closely, it says "unresolved internals" and it says its a linker error through the error code "LNK". Basically, you're referring to functions for which the compiler does not have a definition. The compiler cannot figure out how to construct your exe if you're calling functions which don't technically exist in the current context. You need to let the compiler know that Maximillian exists so that it knows where to go when you're calling the library's functions

**Comment by admin96** [comment]
You need to compile the library first. The libs folder just contains source code which hasn't been compiled

**Comment by goncasmage1** [comment]
And how do i compile the libs folder through VS?

**Comment by admin96** [comment]
You can make it work without compiling/linking a static library. Just import all the source files for each project you're compiling

**Comment by goncasmage1** [comment]
Sorry i'm kinda lost. I already added the libs folder to the VC++ Directories, but i'm not sure which part i should add them to. Probably the header and source directories right? :p

**Comment by admin96** [comment]
Copy/paste all files from libs folder to your project solution and add all the files to the project solution **for each project**

**Comment by admin96** [comment]
This is like the basics of C++, if you can't figure this stuff out, its better to move to [Maxim](https://github.com/micknoise/Maxim)

**Comment by goncasmage1** [comment]
Sorry, i'm kinda new to VS although i do know how to compile C++ code, just confused about how things are organized in VS. I got it to work now thank you for your pacience!

**Comment by admin96** [comment]
No problem. You should close the issue though because there was no problem with the library. Next time just message me here if you have a problem: aimran8332@conestogac.on.ca

**Comment by goncasmage1** [comment]
Ok thank you ;)
